-- zythum sorter
-- tidy up your factorio ui
--
-- written and copyrighted 2016+
-- by sven marc 'cybrox' gehring
--
-- file: data-final-fixes.lua
-- desc: Past-load after all other mods, initialize sorting

require('config')

-- Load mod internal data and libraries from the core
require('core.debug')
require('core.sorter')

-- Load mod prototypes in order to append them to the game
require('prototypes.item-groups')

-- Load separate sorting files for mods in order to rearrange them
if zythum_cfg_enabledebug == false then
  require('mods.compiled')
else
  require('mods.00+Armor')
  require('mods.20x20ArmorMK2')
  require('mods.5dim_automatization')
  require('mods.5dim_battlefield')
  require('mods.5dim_decoration')
  require('mods.5dim_energy')
  require('mods.5dim_logistic')
  require('mods.5dim_mining')
  require('mods.5dim_module')
  require('mods.5dim_resources')
  require('mods.5dim_vehicle')
  require('mods.AddAssemblerBatteries')
  require('mods.Advanced-Drills')
  require('mods.Advanced-Electric')
  require('mods.Advanced-Logistics')
  require('mods.AfraidOfTheDark')
  require('mods.Agent+Orange')
  require('mods.Aircraft')
  require('mods.Algaculture')
  require('mods.Alien+Oil')
  require('mods.AlienArtifacts')
  require('mods.AlienEggs')
  require('mods.AlienWall')
  require('mods.AllFluids')
  require('mods.Alternate+Alien+Science')
  require('mods.AmmoBox')
  require('mods.AquiferDrill')
  require('mods.Artillery')
  require('mods.AssemblyZero')
  require('mods.Auto_Deploy_Destroyers')
  require('mods.AutomaticDeconstruction')
  require('mods.Avatars')
  require('mods.Bergius_Process')
  require('mods.BigDrill')
  require('mods.BigWoodenPowerPole')
  require('mods.Big_Brother')
  require('mods.Big_chest')
  require('mods.Biter-gun')
  require('mods.BridgeRailway')
  require('mods.Burner-Filter-Inserter')
  require('mods.CargoRocket')
  require('mods.Chainsaw')
  require('mods.CharcoalBurner')
  require('mods.CheaperAmmoMaybe')
  require('mods.Equalizer_Chests')
  require('mods.Explosive+Excavation')
  require('mods.Explosive+Termites')
  require('mods.ExtendoReach')
  require('mods.FactorioExtended-Core')
  require('mods.FactorioExtended-Equipment')
  require('mods.FactorioExtended-Logistics')
  require('mods.FactorioExtended-Machines')
  require('mods.FactorioExtended-Power')
  require('mods.FactorioExtended-Transport')
  require('mods.FactorioExtended-Weaponry')
  require('mods.Factorissimo')
  require('mods.additionaloilrefineries')
  require('mods.air-filtering')
  require('mods.alien-science')
  require('mods.base')
  require('mods.beltSorter')
  require('mods.beltplanner')
  require('mods.blueprint-book-2')
  require('mods.bobenemies ')
  require('mods.boblogistics')
  require('mods.bobmining')
  require('mods.bobmodules')
  require('mods.bobores')
  require('mods.bobplates')
  require('mods.bobpower')
  require('mods.bobtech')
  require('mods.boxing')
  require('mods.bulldozer')
  require('mods.burn-the-world')
end
