-- zythum sorter
-- tidy up your factorio ui
--
-- written and copyrighted 2016+
-- by sven marc 'cybrox' gehring
--
-- file: data-final-fixes.lua
-- desc: Past-load after all other mods, initialize sorting

require('config')

-- Load mod internal data and libraries from the core
require('core.debug')
require('core.sorter')

-- Load mod prototypes in order to append them to the game
require('prototypes.item-groups')

-- Load separate sorting files for mods in order to rearrange them
if zythum_cfg_enabledebug == false then
  require('mods.compiled')
else
  require('mods.00+Armor')
  require('mods.20x20ArmorMK2')
  require('mods.5dim_automatization')
  require('mods.5dim_battlefield')
  require('mods.5dim_decoration')
  require('mods.5dim_energy')
  require('mods.5dim_logistic')
  require('mods.5dim_mining')
  require('mods.5dim_module')
  require('mods.5dim_resources')
  require('mods.5dim_vehicle')
  require('mods.AddAssemblerBatteries')
  require('mods.Advanced-Drills')
  require('mods.Advanced-Electric')
  require('mods.Advanced-Logistics')
  require('mods.AfraidOfTheDark')
  require('mods.Agent+Orange')
  require('mods.Aircraft')
  require('mods.Algaculture')
  require('mods.Alien+Oil')
  require('mods.AlienArtifacts')
  require('mods.AlienEggs')
  require('mods.AlienWall')
  require('mods.AllFluids')
  require('mods.Alternate+Alien+Science')
  require('mods.AmmoBox')
  require('mods.AquiferDrill')
  require('mods.Artillery')
  require('mods.AssemblyZero')
  require('mods.Auto_Deploy_Destroyers')
  require('mods.AutomaticDeconstruction')
  require('mods.Avatars')
  require('mods.Bergius_Process')
  require('mods.BigDrill')
  require('mods.BigWoodenPowerPole')
  require('mods.Big_Brother')
  require('mods.Big_chest')
  require('mods.Biter-gun')
  require('mods.BridgeRailway')
  require('mods.Burner-Filter-Inserter')
  require('mods.CargoRocket')
  require('mods.Chainsaw')
  require('mods.CharcoalBurner')
  require('mods.CheaperAmmoMaybe')
  require('mods.CircuitLogger')
  require('mods.CoalToHeavy')
  require('mods.Combat_Units')
  require('mods.Compression+Chests')
  require('mods.Concrete_Lamppost')
  require('mods.CopySettingsTool')
  require('mods.Cursed-PI')
  require('mods.CurvedRail')
  require('mods.DistancePlus')
  require('mods.Drones')
  require('mods.EEMD')
  require('mods.Electric+Furnaces')
  require('mods.ElectricVoid')
  require('mods.Equalizer_Chests')
  require('mods.Explosive+Excavation')
  require('mods.Explosive+Termites')
  require('mods.ExtendoReach')
  require('mods.FARL')
  require('mods.FactorioExtended-Core')
  require('mods.FactorioExtended-Equipment')
  require('mods.FactorioExtended-Logistics')
  require('mods.FactorioExtended-Machines')
  require('mods.FactorioExtended-Power')
  require('mods.FactorioExtended-Transport')
  require('mods.FactorioExtended-Weaponry')
  require('mods.Factorissimo')
  require('mods.Factorissimo_Plus')
  require('mods.Fast_Long_Inserter')
  require('mods.FasterTrains')
  require('mods.Fire_Mine')
  require('mods.Flare')
  require('mods.Flow Control')
  require('mods.Fluid+Void')
  require('mods.FlyTox')
  require('mods.Force Fields')
  require('mods.FusionReactor')
  require('mods.FusionRobots')
  require('mods.GDIW')
  require('mods.GMod')
  require('mods.GeneratorPriority')
  require('mods.Generic_Logistic_Chest')
  require('mods.GroundPrinter')
  require('mods.HandCrankGenerator')
  require('mods.IncendiaryMunitions')
  require('mods.InterfaceChest')
  require('mods.Inventory Sensor')
  require('mods.Item Collectors')
  require('mods.K-ItemDestroyer')
  require('mods.LIQUADO')
  require('mods.Landfill')
  require('mods.Large-Chests')
  require('mods.Lejv-armor')
  require('mods.Loader-Furnace')
  require('mods.LogisticsMining')
  require('mods.Longer_Underground_Pipes')
  require('mods.MK2-Mod')
  require('mods.MagneticFloor')
  require('mods.Megamind')
  require('mods.Military_Research_5')
  require('mods.MiniBasicStart')
  require('mods.MiniPorts')
  require('mods.MiningTools')
  require('mods.Misanthrope')
  require('mods.Mk3 Armor')
  require('mods.Modular-Armor')
  require('mods.ModuleInserter')
  require('mods.N-Tech Chemistry')
  require('mods.Omnibarrels')
  require('mods.OverMods')
  require('mods.Oxygen')
  require('mods.PeaceModeOre')
  require('mods.PeppeBotStart')
  require('mods.PersonalTeleporter')
  require('mods.Personal_Spawns')
  require('mods.Piano_Player')
  require('mods.Plasma Shotgun Shells')
  require('mods.Potato')
  require('mods.PowerAndArmor')
  require('mods.RFM-transport')
  require('mods.RailTanker')
  require('mods.Raven')
  require('mods.Realism')
  require('mods.Red Alerts')
  require('mods.Red_Assembling_Machine')
  require('mods.Reinforced-Walls')
  require('mods.Resource-Conversions')
  require('mods.RoadWorks')
  require('mods.Robo-Charge')
  require('mods.Satellite Uplink Station')
  require('mods.SatelliteRadar')
  require('mods.ScienceCostTweaker')
  require('mods.Screenshot_Tool')
  require('mods.Sensor')
  require('mods.ShevanSolar')
  require('mods.Shinys-parkingzone')
  require('mods.Ships')
  require('mods.ShuttleTrain')
  require('mods.Signposts')
  require('mods.SmartDisplay')
  require('mods.SmartSplitters')
  require('mods.SpaceMod')
  require('mods.Stainless Steel Wagon')
  require('mods.StrangeMatter')
  require('mods.Suit-Plug')
  require('mods.SuperChest')
  require('mods.SuperTank')
  require('mods.Tank Gun')
  require('mods.Tank Wagon')
  require('mods.TankRoboport')
  require('mods.Tape Measure')
  require('mods.Tesseract')
  require('mods.TheLongNauvis')
  require('mods.The_Lab')
  require('mods._M_Armor')
  require('mods.additionaloilrefineries')
  require('mods.air-filtering')
  require('mods.alien-science')
  require('mods.base')
  require('mods.beltSorter')
  require('mods.beltplanner')
  require('mods.blueprint-book-2')
  require('mods.bobassembly')
  require('mods.bobelectronics')
  require('mods.bobenemies ')
  require('mods.bobgreenhouse')
  require('mods.boblogistics')
  require('mods.bobmining')
  require('mods.bobmodules')
  require('mods.bobores')
  require('mods.bobplates')
  require('mods.bobpower')
  require('mods.bobtech')
  require('mods.bobwarfare')
  require('mods.boxing')
  require('mods.bulldozer')
  require('mods.burn-the-world')
  require('mods.color-coding')
  require('mods.compoundsplitters')
  require('mods.deforest-planner')
  require('mods.dynamic-train-stop')
  require('mods.electric_ghost_car')
  require('mods.fish-sandwich')
  require('mods.flamenades')
  require('mods.flownetwork')
  require('mods.fluid-barrel')
  require('mods.gimprovements')
  require('mods.launch-control')
  require('mods.magnet')
  require('mods.makkariutils')
  require('mods.militarization')
  require('mods.mini-machines')
  require('mods.moindustry')
  require('mods.momining')
  require('mods.mopower')
  require('mods.mosurvival')
  require('mods.ore-eraser')
  require('mods.peacemod')
  require('mods.pollution-detector')
  require('mods.robotarmy')
  require('mods.security-camera')
  require('mods.space-platform')
  require('mods.spawn-belt')
  require('mods.spawn-pump')
end
