-- zythum sorter
-- tidy up your factorio ui
--
-- file: mods/bobmodules.lua
-- name: Bob's Modules
-- link: https://mods.factorio.com/mods/Bobingabout/bobmodules
-- author: cybrox
-- refver: 0.13.0

zythum_sort_mod('bobmodules')


-- Recipes for category zythum-modules
zythum_sort('modules',      01, 01, 'beacon-2')
zythum_sort('modules',      01, 02, 'beacon-3')

zythum_sort('modules',      01, 03, 'lab-module')

zythum_sort('modules',      02, 01, 'speed-module-4')
zythum_sort('modules',      02, 02, 'speed-module-5')
zythum_sort('modules',      02, 03, 'speed-module-6')
zythum_sort('modules',      02, 04, 'speed-module-7')
zythum_sort('modules',      02, 05, 'speed-module-8')
zythum_sort('modules',      02, 06, 'raw-speed-module-1')
zythum_sort('modules',      02, 07, 'raw-speed-module-2')
zythum_sort('modules',      02, 08, 'raw-speed-module-3')
zythum_sort('modules',      02, 09, 'raw-speed-module-4')
zythum_sort('modules',      02, 10, 'raw-speed-module-5')
zythum_sort('modules',      02, 11, 'raw-speed-module-6')
zythum_sort('modules',      02, 12, 'raw-speed-module-7')
zythum_sort('modules',      02, 13, 'raw-speed-module-8')

zythum_sort('modules',      03, 01, 'productivity-module-4')
zythum_sort('modules',      03, 02, 'productivity-module-5')
zythum_sort('modules',      03, 03, 'productivity-module-6')
zythum_sort('modules',      03, 04, 'productivity-module-7')
zythum_sort('modules',      03, 05, 'productivity-module-8')
zythum_sort('modules',      03, 06, 'raw-productivity-module-1')
zythum_sort('modules',      03, 07, 'raw-productivity-module-2')
zythum_sort('modules',      03, 08, 'raw-productivity-module-3')
zythum_sort('modules',      03, 09, 'raw-productivity-module-4')
zythum_sort('modules',      03, 10, 'raw-productivity-module-5')
zythum_sort('modules',      03, 11, 'raw-productivity-module-6')
zythum_sort('modules',      03, 12, 'raw-productivity-module-7')
zythum_sort('modules',      03, 13, 'raw-productivity-module-8')

zythum_sort('modules',      04, 01, 'effectivity-module-4')
zythum_sort('modules',      04, 02, 'effectivity-module-5')
zythum_sort('modules',      04, 03, 'effectivity-module-6')
zythum_sort('modules',      04, 04, 'effectivity-module-7')
zythum_sort('modules',      04, 05, 'effectivity-module-8')

zythum_sort('modules',      05, 01, 'pollution-clean-module-1')
zythum_sort('modules',      05, 02, 'pollution-clean-module-2')
zythum_sort('modules',      05, 03, 'pollution-clean-module-3')
zythum_sort('modules',      05, 04, 'pollution-clean-module-4')
zythum_sort('modules',      05, 05, 'pollution-clean-module-5')
zythum_sort('modules',      05, 06, 'pollution-clean-module-6')
zythum_sort('modules',      05, 07, 'pollution-clean-module-7')
zythum_sort('modules',      05, 08, 'pollution-clean-module-8')

zythum_sort('modules',      06, 01, 'pollution-create-module-1')
zythum_sort('modules',      06, 02, 'pollution-create-module-2')
zythum_sort('modules',      06, 03, 'pollution-create-module-3')
zythum_sort('modules',      06, 04, 'pollution-create-module-4')
zythum_sort('modules',      06, 05, 'pollution-create-module-5')
zythum_sort('modules',      06, 06, 'pollution-create-module-6')
zythum_sort('modules',      06, 07, 'pollution-create-module-7')
zythum_sort('modules',      06, 08, 'pollution-create-module-8')

zythum_sort('modules',      07, 01, 'module-case')
zythum_sort('modules',      07, 02, 'module-contact')
zythum_sort('modules',      07, 03, 'module-circuit-board')
zythum_sort('modules',      07, 04, 'module-processor-board')
zythum_sort('modules',      07, 05, 'module-processor-board-2')
zythum_sort('modules',      07, 06, 'module-processor-board-3')
zythum_sort('modules',      07, 07, 'green-module-1')
zythum_sort('modules',      07, 08, 'green-module-2')
zythum_sort('modules',      07, 09, 'green-module-3')
zythum_sort('modules',      07, 10, 'green-module-4')
zythum_sort('modules',      07, 11, 'green-module-5')
zythum_sort('modules',      07, 12, 'green-module-6')
zythum_sort('modules',      07, 13, 'green-module-7')
zythum_sort('modules',      07, 14, 'green-module-8')

zythum_sort('modules',      08, 01, 'speed-processor')
zythum_sort('modules',      08, 02, 'speed-processor-2')
zythum_sort('modules',      08, 03, 'speed-processor-3')
zythum_sort('modules',      08, 04, 'effectivity-processor')
zythum_sort('modules',      08, 05, 'effectivity-processor-2')
zythum_sort('modules',      08, 06, 'effectivity-processor-3')
zythum_sort('modules',      08, 07, 'productivity-processor')
zythum_sort('modules',      08, 08, 'productivity-processor-2')
zythum_sort('modules',      08, 09, 'productivity-processor-3')
zythum_sort('modules',      08, 10, 'pollution-clean-processor')
zythum_sort('modules',      08, 11, 'pollution-clean-processor-2')
zythum_sort('modules',      08, 12, 'pollution-clean-processor-3')
zythum_sort('modules',      08, 13, 'pollution-create-processor')
zythum_sort('modules',      08, 14, 'pollution-create-processor-2')
zythum_sort('modules',      08, 15, 'pollution-create-processor-3')

zythum_sort('modules',      09, 01, 'raw-speed-module-1-combine')
zythum_sort('modules',      09, 02, 'raw-speed-module-2-combine')
zythum_sort('modules',      09, 03, 'raw-speed-module-3-combine')
zythum_sort('modules',      09, 04, 'raw-speed-module-4-combine')
zythum_sort('modules',      09, 05, 'raw-speed-module-5-combine')
zythum_sort('modules',      09, 06, 'raw-speed-module-6-combine')
zythum_sort('modules',      09, 07, 'raw-speed-module-7-combine')
zythum_sort('modules',      09, 08, 'raw-speed-module-8-combine')
zythum_sort('modules',      09, 09, 'green-module-1-combine')
zythum_sort('modules',      09, 10, 'green-module-2-combine')
zythum_sort('modules',      09, 11, 'green-module-3-combine')
zythum_sort('modules',      09, 12, 'green-module-4-combine')
zythum_sort('modules',      09, 13, 'green-module-5-combine')
zythum_sort('modules',      09, 14, 'green-module-6-combine')
zythum_sort('modules',      09, 15, 'green-module-7-combine')
zythum_sort('modules',      09, 16, 'green-module-8-combine')
zythum_sort('modules',      09, 17, 'raw-productivity-module-1-combine')
zythum_sort('modules',      09, 18, 'raw-productivity-module-2-combine')
zythum_sort('modules',      09, 19, 'raw-productivity-module-3-combine')
zythum_sort('modules',      09, 20, 'raw-productivity-module-4-combine')
zythum_sort('modules',      09, 21, 'raw-productivity-module-5-combine')
zythum_sort('modules',      09, 22, 'raw-productivity-module-6-combine')
zythum_sort('modules',      09, 23, 'raw-productivity-module-7-combine')
zythum_sort('modules',      09, 24, 'raw-productivity-module-8-combine')
