-- zythum sorter
-- tidy up your factorio ui
--
-- file: mods/bobplates.lua
-- name: Bob's Metals, Chemicals and Intermediates
-- link: https://mods.factorio.com/mods/Bobingabout/bobplates
-- author: cybrox
-- refver: 0.13.2

zythum_sort_mod('bobplates')


-- Recipes for category zythum-transport
zythum_sort('transport',     08, 01, 'water-pump')
zythum_sort('transport',     08, 02, 'water-pump-2')
zythum_sort('transport',     08, 03, 'water-pump-3')
zythum_sort('transport',     08, 04, 'water-pump-4')
zythum_sort('transport',     08, 05, 'air-pump')
zythum_sort('transport',     08, 06, 'air-pump-2')
zythum_sort('transport',     08, 07, 'air-pump-3')
zythum_sort('transport',     08, 08, 'air-pump-4')
zythum_sort('transport',     09, 01, 'void-pump')

-- Recipes for category zythum-production
zythum_sort('production',    01, 01, 'mixing-furnace')
zythum_sort('production',    01, 02, 'electric-mixing-furnace')
zythum_sort('production',    01, 03, 'chemical-furnace')
zythum_sort('production',    01, 04, 'chemical-boiler')
zythum_sort('production',    07, 01, 'electrolyser')

-- Recipes for category zythum-chemistry
zythum_sort('chemistry',     01, 01, 'bob-oil-processing')
zythum_sort('chemistry',     01, 02, 'petroleum-gas-cracking')
zythum_sort('chemistry',     01, 03, 'salt')
zythum_sort('chemistry',     01, 04, 'hydrogen')
zythum_sort('chemistry',     01, 05, 'oxygen')
zythum_sort('chemistry',     01, 06, 'nitrogen')
zythum_sort('chemistry',     01, 07, 'alumina')
zythum_sort('chemistry',     01, 08, 'chlorine')
zythum_sort('chemistry',     01, 09, 'liquid-air')
zythum_sort('chemistry',     01, 09, 'bob-liquid-air')
zythum_sort('chemistry',     01, 10, 'lithia-water')
zythum_sort('chemistry',     06, 01, 'liquid-fuel')

zythum_sort('chemistry',     02, 02, 'sulfur-2')
zythum_sort('chemistry',     02, 03, 'sulfur-dioxide')
zythum_sort('chemistry',     02, 04, 'nitrogen-dioxide')
zythum_sort('chemistry',     02, 05, 'hydrogen-chloride')
zythum_sort('chemistry',     02, 06, 'nitric-acid')
zythum_sort('chemistry',     02, 07, 'tungstic-acid')
zythum_sort('chemistry',     02, 08, 'sulfuric-acid-2')
zythum_sort('chemistry',     02, 09, 'silicon-nitride')
zythum_sort('chemistry',     02, 10, 'ferric-chloride-solution')

zythum_sort('chemistry',     03, 01, 'lithium-chloride')
zythum_sort('chemistry',     03, 02, 'calcium-chloride')
zythum_sort('chemistry',     03, 03, 'lead-oxide')
zythum_sort('chemistry',     03, 04, 'silver-nitrate')
zythum_sort('chemistry',     03, 05, 'silver-oxide')
zythum_sort('chemistry',     03, 06, 'tungsten-oxide')
zythum_sort('chemistry',     03, 07, 'powdered-tungsten')
zythum_sort('chemistry',     03, 08, 'cobalt-oxide')
zythum_sort('chemistry',     03, 09, 'cobalt-oxide-from-copper')
zythum_sort('chemistry',     03, 10, 'silver-from-lead')
zythum_sort('chemistry',     03, 11, 'lithium-cobalt-oxide')
zythum_sort('chemistry',     03, 12, 'tungsten-carbide')
zythum_sort('chemistry',     03, 13, 'tungsten-carbide-2')
zythum_sort('chemistry',     03, 14, 'lithium-perchlorate')
zythum_sort('chemistry',     03, 15, 'sodium-hydroxide')

zythum_sort('chemistry',     04, 01, 'silicon-carbide')
zythum_sort('chemistry',     04, 02, 'silicon-wafer')
zythum_sort('chemistry',     04, 03, 'silicon-powder')

zythum_sort('chemistry',     06, 01, 'solid-fuel-from-hydrogen')

zythum_sort('chemistry',     08, 01, 'water-electrolysis')
zythum_sort('chemistry',     08, 02, 'salt-water-electrolysis')
zythum_sort('chemistry',     08, 03, 'lithium-water-electrolysis')

zythum_sort('chemistry',     09, 01, 'void-oxygen')
zythum_sort('chemistry',     09, 02, 'void-hydrogen')
zythum_sort('chemistry',     09, 03, 'void-nitrogen')
zythum_sort('chemistry',     09, 04, 'void-chlorine')
zythum_sort('chemistry',     09, 05, 'void-sulfur-dioxide')

-- Recipes for category zythum-intermediate
zythum_sort('intermediate',  04, 01, 'gunmetal-alloy')
zythum_sort('intermediate',  04, 02, 'invar-alloy')
zythum_sort('intermediate',  04, 03, 'nitinol-alloy')
zythum_sort('intermediate',  04, 04, 'cobalt-steel-alloy')
zythum_sort('intermediate',  04, 05, 'bronze-alloy')
zythum_sort('intermediate',  04, 06, 'brass-alloy')
zythum_sort('intermediate',  04, 07, 'electrum-alloy')
zythum_sort('intermediate',  04, 08, 'copper-tungsten-alloy')
zythum_sort('intermediate',  05, 01, 'steel-gear-wheel')
zythum_sort('intermediate',  05, 02, 'brass-gear-wheel')
zythum_sort('intermediate',  05, 03, 'tungsten-gear-wheel')
zythum_sort('intermediate',  05, 04, 'nitinol-gear-wheel')
zythum_sort('intermediate',  05, 05, 'titanium-gear-wheel')
zythum_sort('intermediate',  06, 01, 'steel-bearing-ball')
zythum_sort('intermediate',  06, 02, 'titanium-bearing-ball')
zythum_sort('intermediate',  06, 03, 'nitinol-bearing-ball')
zythum_sort('intermediate',  06, 04, 'ceramic-bearing-ball')
zythum_sort('intermediate',  07, 01, 'steel-bearing')
zythum_sort('intermediate',  07, 02, 'titanium-bearing')
zythum_sort('intermediate',  07, 03, 'nitinol-bearing')
zythum_sort('intermediate',  07, 04, 'ceramic-bearing')
zythum_sort('intermediate',  08, 01, 'grinding-wheel')
zythum_sort('intermediate',  08, 02, 'polishing-compound')
zythum_sort('intermediate',  08, 03, 'polishing-wheel')
zythum_sort('intermediate',  08, 04, 'polishing-wheel-synthetic')
zythum_sort('intermediate',  02, 01, 'advanced-processing-unit')
zythum_sort('intermediate',  02, 02, 'lithium-ion-battery')
zythum_sort('intermediate',  02, 03, 'silver-zinc-battery')

-- Recipes for category zythum-resources
zythum_sort('resources',     01, 01, 'bob-resin-wood')
zythum_sort('resources',     01, 02, 'synthetic-wood')
zythum_sort('resources',     01, 03, 'bob-resin-oil')
zythum_sort('resources',     01, 04, 'resin')
zythum_sort('resources',     01, 05, 'rubber')
zythum_sort('resources',     01, 05, 'bob-rubber')

zythum_sort('resources',     02, 01, 'tin-ore')
zythum_sort('resources',     02, 02, 'lead-ore')
zythum_sort('resources',     02, 03, 'quartz')
zythum_sort('resources',     02, 04, 'silver-ore')
zythum_sort('resources',     02, 05, 'zinc-ore')
zythum_sort('resources',     02, 06, 'gold-ore')
zythum_sort('resources',     02, 07, 'bauxite-ore')
zythum_sort('resources',     02, 08, 'rutile-ore')
zythum_sort('resources',     02, 09, 'tungsten-ore')
zythum_sort('resources',     02, 01, 'nickel-ore')
zythum_sort('resources',     02, 02, 'cobalt-ore')

zythum_sort('resources',     04, 01, 'glass')
zythum_sort('resources',     04, 02, 'quartz-glass')
zythum_sort('resources',     03, 06, 'void')
zythum_sort('resources',     04, 03, 'silicon')
zythum_sort('resources',     04, 04, 'lithium')
zythum_sort('resources',     04, 05, 'carbon')

zythum_sort('resources',     04, 06, 'gem-ore')
zythum_sort('resources',     04, 07, 'ruby-ore')
zythum_sort('resources',     04, 08, 'sapphire-ore')
zythum_sort('resources',     04, 09, 'emerald-ore')
zythum_sort('resources',     04, 10, 'amethyst-ore')
zythum_sort('resources',     04, 11, 'topaz-ore')
zythum_sort('resources',     04, 12, 'diamond-ore')

zythum_sort('resources',     05, 01, 'bob-ruby-3')
zythum_sort('resources',     05, 02, 'bob-sapphire-3')
zythum_sort('resources',     05, 03, 'bob-emerald-3')
zythum_sort('resources',     05, 04, 'bob-amethyst-3')
zythum_sort('resources',     05, 05, 'bob-topaz-3')
zythum_sort('resources',     05, 06, 'bob-diamond-3')
zythum_sort('resources',     06, 01, 'bob-ruby-4')
zythum_sort('resources',     06, 02, 'bob-sapphire-4')
zythum_sort('resources',     06, 03, 'bob-emerald-4')
zythum_sort('resources',     06, 04, 'bob-amethyst-4')
zythum_sort('resources',     06, 05, 'bob-topaz-4')
zythum_sort('resources',     06, 06, 'bob-diamond-4')
zythum_sort('resources',     07, 01, 'bob-ruby-5')
zythum_sort('resources',     07, 02, 'bob-sapphire-5')
zythum_sort('resources',     07, 03, 'bob-emerald-5')
zythum_sort('resources',     07, 04, 'bob-amethyst-5')
zythum_sort('resources',     07, 05, 'bob-topaz-5')
zythum_sort('resources',     07, 06, 'bob-diamond-5')

zythum_sort('resources',     05, 01, 'ruby-3')
zythum_sort('resources',     05, 02, 'sapphire-3')
zythum_sort('resources',     05, 03, 'emerald-3')
zythum_sort('resources',     05, 04, 'amethyst-3')
zythum_sort('resources',     05, 05, 'topaz-3')
zythum_sort('resources',     05, 06, 'diamond-3')
zythum_sort('resources',     06, 01, 'ruby-4')
zythum_sort('resources',     06, 02, 'sapphire-4')
zythum_sort('resources',     06, 03, 'emerald-4')
zythum_sort('resources',     06, 04, 'amethyst-4')
zythum_sort('resources',     06, 05, 'topaz-4')
zythum_sort('resources',     06, 06, 'diamond-4')
zythum_sort('resources',     07, 01, 'ruby-5')
zythum_sort('resources',     07, 02, 'sapphire-5')
zythum_sort('resources',     07, 03, 'emerald-5')
zythum_sort('resources',     07, 04, 'amethyst-5')
zythum_sort('resources',     07, 05, 'topaz-5')
zythum_sort('resources',     07, 06, 'diamond-5')

zythum_sort('resources',     09, 01, 'sort-gem-ore')
zythum_sort('resources',     09, 02, 'coal-cracking')

-- Recipes for category zythum-plates
zythum_sort('plates',        01, 01, 'silver-plate')
zythum_sort('plates',        01, 02, 'tin-plate')
zythum_sort('plates',        01, 03, 'cobalt-plate')
zythum_sort('plates',        01, 04, 'gold-plate')
zythum_sort('plates',        01, 05, 'bob-gold-plate')
zythum_sort('plates',        01, 06, 'nickel-plate')
zythum_sort('plates',        01, 07, 'bob-nickel-plate')
zythum_sort('plates',        01, 08, 'zinc-plate')
zythum_sort('plates',        01, 09, 'bob-zinc-plate')
zythum_sort('plates',        01, 10, 'aluminium-plate')
zythum_sort('plates',        01, 11, 'bob-aluminium-plate')
zythum_sort('plates',        01, 12, 'titanium-plate')
zythum_sort('plates',        01, 13, 'bob-titanium-plate')
zythum_sort('plates',        01, 14, 'tungsten-plate')
zythum_sort('plates',        01, 15, 'bob-tungsten-plate')
zythum_sort('plates',        01, 16, 'lead-plate')
zythum_sort('plates',        01, 17, 'bob-lead-plate')
zythum_sort('plates',        01, 18, 'bob-silicon-plate')
zythum_sort('plates',        02, 01, 'alien-blue-alloy')
zythum_sort('plates',        02, 02, 'alien-orange-alloy')

-- Recipes for category zythum-liquids
zythum_sort('liquids',       01, 01, 'water-barrel')
zythum_sort('liquids',       01, 02, 'bob-empty-crude-oil-barrel')

zythum_sort('liquids',       02, 01, 'empty-hydrogen-canister')
zythum_sort('liquids',       02, 02, 'empty-oxygen-canister')
zythum_sort('liquids',       02, 03, 'empty-nitrogen-canister')
zythum_sort('liquids',       02, 04, 'empty-chlorine-canister')
zythum_sort('liquids',       02, 05, 'empty-hydrogen-chloride-canister')
zythum_sort('liquids',       02, 06, 'empty-petroleum-gas-canister')
zythum_sort('liquids',       02, 07, 'empty-heavy-oil-barrel')
zythum_sort('liquids',       02, 08, 'empty-light-oil-barrel')
zythum_sort('liquids',       02, 09, 'empty-lubricant-barrel')
zythum_sort('liquids',       03, 01, 'empty-sulfuric-acid-barrel')
zythum_sort('liquids',       03, 02, 'empty-water-barrel')
zythum_sort('liquids',       03, 03, 'empty-lithia-water-barrel')
zythum_sort('liquids',       03, 04, 'empty-nitric-acid-barrel')
zythum_sort('liquids',       03, 05, 'empty-liquid-fuel-canister')
zythum_sort('liquids',       03, 06, 'empty-ferric-chloride-canister')
zythum_sort('liquids',       03, 07, 'empty-alien-acid-barrel')
zythum_sort('liquids',       03, 08, 'empty-alien-explosive-barrel')
zythum_sort('liquids',       03, 09, 'empty-alien-poison-barrel')
zythum_sort('liquids',       03, 10, 'empty-alien-fire-barrel')

zythum_sort('liquids',       04, 01, 'fill-heavy-oil-barrel')
zythum_sort('liquids',       04, 02, 'fill-light-oil-barrel')
zythum_sort('liquids',       04, 03, 'fill-lubricant-barrel')
zythum_sort('liquids',       04, 04, 'fill-sulfuric-acid-barrel')
zythum_sort('liquids',       04, 05, 'fill-water-barrel')
zythum_sort('liquids',       04, 06, 'fill-lithia-water-barrel')
zythum_sort('liquids',       04, 07, 'fill-nitric-acid-barrel')
zythum_sort('liquids',       04, 08, 'bob-fill-crude-oil-barrel')
zythum_sort('liquids',       05, 01, 'fill-alien-acid-barrel')
zythum_sort('liquids',       05, 02, 'fill-alien-explosive-barrel')
zythum_sort('liquids',       05, 03, 'fill-alien-poison-barrel')
zythum_sort('liquids',       05, 04, 'fill-alien-fire-barrel')

zythum_sort('liquids',       06, 01, 'heavy-oil-barrel')
zythum_sort('liquids',       06, 02, 'light-oil-barrel')
zythum_sort('liquids',       06, 03, 'lubricant-barrel')
zythum_sort('liquids',       06, 04, 'sulfuric-acid-barrel')
zythum_sort('liquids',       06, 05, 'nitric-acid-barrel')
zythum_sort('liquids',       06, 06, 'lithia-water-barrel')
zythum_sort('liquids',       06, 07, 'gas-canister')
zythum_sort('liquids',       06, 08, 'empty-canister')
zythum_sort('liquids',       06, 09, 'oxygen-canister')
zythum_sort('liquids',       06, 10, 'nitrogen-canister')
zythum_sort('liquids',       06, 11, 'chlorine-canister')
zythum_sort('liquids',       06, 12, 'hydrogen-canister')
zythum_sort('liquids',       06, 13, 'hydrogen-chloride-canister')
zythum_sort('liquids',       06, 14, 'petroleum-gas-canister')
zythum_sort('liquids',       06, 15, 'liquid-fuel-canister')
zythum_sort('liquids',       06, 16, 'ferric-chloride-canister')
zythum_sort('liquids',       06, 17, 'alien-acid-barrel')
zythum_sort('liquids',       06, 18, 'alien-explosive-barrel')
zythum_sort('liquids',       06, 19, 'alien-poison-barrel')
zythum_sort('liquids',       06, 20, 'alien-fire-barrel')

zythum_sort('liquids',       08, 01, 'alien-acid')
zythum_sort('liquids',       08, 02, 'alien-explosive')
zythum_sort('liquids',       08, 03, 'alien-poison')
zythum_sort('liquids',       08, 04, 'alien-fire')
